README.md

Pointing now to relative markdown docs in the repo instead of the original Google doc.

Update readme to point to newly added docs

---

.ci-scripts/release/build-docker-images-on-release.bash
.ci-scripts/release/build-latest-docker-images.bash
.github/workflows/pr.yml

Adding `--pull` will avoid using an out-of-date base image if a
more recent one is available.

Make sure we use most up-to-date base images

---

corral/bundle/bundle.pony
corral/cmd/cmd_add.pony
corral/cmd/cmd_clean.pony
corral/cmd/cmd_fetch.pony
corral/cmd/cmd_info.pony
corral/cmd/cmd_init.pony
corral/cmd/cmd_list.pony
corral/cmd/cmd_remove.pony
corral/cmd/cmd_run.pony
corral/cmd/cmd_update.pony
corral/cmd/context.pony
corral/main.pony
corral/test/main.pony

This change allows us to provide a directory for creating and loading both `corral.json` and `dep-lock.json` files. It affects most commands as they mostly need to load the file before doing their job. So, from now on, we can pass the `--path "path/to/the/bundle/dir/"` argument.
```bash
corral[master] % mkdir tmp
corral[master] % corral init --path tmp
init: from dir tmp
INFO: Created bundle in /Users/ordepdev/Work/corral/tmp
FINE: Going to write /Users/ordepdev/Work/corral/tmp/corral.json
INFO: Writing /Users/ordepdev/Work/corral/tmp/corral.json
FINE: Going to write /Users/ordepdev/Work/corral/tmp/lock.json
INFO: Writing /Users/ordepdev/Work/corral/tmp/lock.json
INFO: init: created: tmp
```
Solves https://github.com/ponylang/corral/issues/23.

Add --path flag

---

corral/cmd/cmd_run.pony
corral/cmd/context.pony
corral/main.pony

Run command no longer requires a corral.json bundle file. 
Removed extraneous envs.
Fixes #22

Fix `corral run` should work if there is no corral.json

---

corral/bundle/bundle.pony
corral/cli.pony
corral/cmd/cmd_add.pony
corral/cmd/cmd_clean.pony
corral/cmd/cmd_fetch.pony
corral/cmd/cmd_info.pony
corral/cmd/cmd_init.pony
corral/cmd/cmd_list.pony
corral/cmd/cmd_remove.pony
corral/cmd/cmd_run.pony
corral/cmd/cmd_update.pony
corral/cmd/cmd_version.pony
corral/cmd/context.pony
corral/main.pony
corral/test/integration/test_version.pony
corral/util/log.pony

- Cleaned logs vs user output:
- Debug log level is set with --debug
- User output level is set with --quiet and --verbose
- Implemented --nothing everywhere.
- Added missing remove command implementation.
Fixes:
ponylang#61 and ponylang#24: Logs vs user output.
ponylang#27: --nothing/-n implemented

Cleaned logs vs user output, implemented --nothing, fixed 'remove' command

---

.github/workflows/release.yml
README.md
RELEASE_PROCESS.md

This shouldn't be merged until corral is added to homebrew.
There is currently a PR open to add it:
https://github.com/Homebrew/homebrew-core/pull/48075

Add macOS releases via Homebrew

---

.ci-scripts/release/x86-64-apple-darwin-nightly.bash
.ci-scripts/release/x86-64-apple-darwin-release.bash
.github/workflows/nightlies.yml
.github/workflows/release.yml

Note that we need ponyc to build these. As of yet, we can't use
ponyup to create the environment, so for now, we install ponyc
via Homebrew.
Once ponyup is available on macOS, we should replace the
`brew install ponyc` with the installation of ponyup and ponyc
via it.

Create macOS .tar.gz packages

---

corral/cmd/cmd_run.pony
corral/vcs/git.pony

If a Runner critical to the correct result of corral fails then it is
better to have all of corral exit immediately (passing through the exit
code). For example, if a git pull fails to execute, we could continue to
compile the project with the wrong code ending with an incorrect result.
Another common example when ponyc compile fails and you are using corral
in a larger make system, you want the make system to know the command
failed.

Pass exit codes from Runners to early exit corral with same code

---

corral/test/util.pony
corral/util/action.pony

The `ProcessError` types from the stdlib `process` package now store their own error messages.
Fixes #88.

Update to handle new `ProcessError` types

---

.ci-scripts/macOS-install-pony-tools.bash
.ci-scripts/release/x86-64-apple-darwin-nightly.bash
.ci-scripts/release/x86-64-apple-darwin-release.bash
.github/workflows/nightlies.yml
.github/workflows/release.yml

Our nightly builds are failing (and our release builds will fail) because
homebrew doesn't have the latest ponyc compiler. As ponyup is now our
officially supported macOS ponyc installation tool, we need to use it
as part of our nightly and release builds to prevent breakage going
forward.

Install ponyc on macOS via ponyup

---

CHANGELOG.md

There's no code in corral for this, it will be fixed by compiling with a
later version of the runtime.
do not merge until a version of pony later than 0.35.0 has been released.

Add "fixed pony rt bug" changelog

---

corral/util/action.pony

Printing stdout as a string will replace `"\n"` with `"\r\n"`.  Since the contents of stdout already have `"\r\n"`, the eventual output on Windows will have `"\r\r\n"`.  This will cause the output to have extra lines in PowerShell.
This PR removes CRs (`"\r"`) from the stdout and stderr strings to avoid this.
This is a minor cosmetic change.

Remove extraneous CR in outputs on Windows

---

corral/cmd/cmd_run.pony

Use correct path separator in PONYPATH on Windows

---

corral/bundle/_flatttened.pony
corral/bundle/dep.pony
corral/bundle/locator.pony

Move Locator out of deps.pony to make it easier to find via fuzzy search
and better fits how the code base is organized.

Move Locator to its own file

---

corral/cmd/cmd_add.pony
corral/cmd/cmd_clean.pony
corral/cmd/cmd_fetch.pony
corral/cmd/cmd_info.pony
corral/cmd/cmd_init.pony
corral/cmd/cmd_list.pony
corral/cmd/cmd_remove.pony
corral/cmd/cmd_run.pony
corral/cmd/cmd_type.pony
corral/cmd/cmd_update.pony
corral/cmd/cmd_version.pony
corral/cmd/executor.pony
corral/vcs/vcs.pony
corral/vcs/vcs_builder.pony

This removes a primitive that had a match statement and moves
the functionality into a class that will be able to build a VCS
for use by commands.
This is a small step towards making commands unit-testable.

Add VCSBuilder class

---

corral/cmd/_test.pony
corral/cmd/_test_cmd_update.pony
corral/cmd/cmd_add.pony
corral/cmd/cmd_clean.pony
corral/cmd/cmd_fetch.pony
corral/cmd/cmd_info.pony
corral/cmd/cmd_init.pony
corral/cmd/cmd_list.pony
corral/cmd/cmd_remove.pony
corral/cmd/cmd_run.pony
corral/cmd/cmd_type.pony
corral/cmd/cmd_update.pony
corral/cmd/cmd_version.pony
corral/cmd/executor.pony
corral/cmd/result_receiver.pony
corral/test/_test.pony
corral/vcs/vcs_builder.pony

As part of the work on #120, an error when using the update command,
I wanted to add tests to demonstrate the bug and then show that the
bug was fixed by my changes.
This is problematic because there are no real unit tests for any
commands.
This commit is the first step in providing better unit testability
of various parts of corral in general and commands specifically.
The only test added by this commit is that when using a corral.json
with empty deps, that no VCS operations will be executed by _Updater.
There are a number of changes that are brought in my this initial refactor.
As we move forward with making corral more testable, some of these changes
will probably fall away. I did what I considered the minimal thing to get
a harness for testing _Updater working. This harness should be …

Baby steps towards making CmdUpdate unit testable

---

corral/main.pony
corral/test/integration/test_fetch.pony
corral/test/integration/test_update.pony

This updates most non-log prints to stdout to have a log level of fine
such that they will only be displayed when the --verbose flag is passed.
Some commands are ommitted from this change, such as info, version, and
list as their explicit purpose is to print information.
Fixes #101 
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Make corral less verbose

---

.release-notes/160.md
corral/cmd/cmd_fetch.pony
corral/cmd/cmd_update.pony

I believe `PostFetchScript` was intended to be called after the fetch was complete. But the call was placed such that it was running in parallel with the fetch. I noticed on the first fetch of a new repo that it doesn't find a bundle file, since the repo hasn't finished cloning yet.

Run PostFetchScript after fetch completion

---

corral/main.pony
corral/test/_test.pony

Corral as currently constituted doesn't need the cycle detector so,
it ends up just slowing the app down. But not a slow down you would
notice.
The bigger issue is that there is a race condition in the runtime
at the moment that is present when the cycle detector is on and
running corral tests triggers it sometimes.
Until that issue is addressed, we should turn the cycle detector
off so we don't get failures from a known source that we don't need to
get them from.

Turn off cycle detector when running corral

---

.release-notes/164.md
corral/bundle/json.pony
corral/test/integration/test_info.pony

Prior to this commit, optional fields were being removed from corral.json.
For things like "info" that we want people to fill out, this is detrimenal
as there is no template for what to fill out.
Given that this is only impacting on "info", I think it makes sense to
change the behavior.

Don't remove empty fields from configuration

---

.release-notes/166.md
corral/bundle/data.pony
doc/design.md

As part of the work I am doing on the pony library documentation
generation, this documentation_url is needed.
The documentation_url will allow a library to link to the documentation
of its dependencies from within its own documentation.

Add documentation_url to `info` section of `corral.json`

---

corral/bundle/bundle.pony
corral/bundle/data.pony

The `packages` field is a new experimental field that will list all
packages that are part of a bundle that should be included for distribution.
At the moment, entries must be added by hand, this commit assures that
any that exist are not removed when corral manipulates the corral.json file.
Eventually, if this feature holds, we will have commands to add and remove
packages as well as a command to prepare for release. Releases, rather than
being a "repo over here with tag" can be hosted on services like GitHub packages
or cloudsmith and would only include the bare minumum needed for the package.
Initially, this field is being used to generate documentation that works across
library projects. Existing exploratory work for that is being done in the
ponylang/library-documentation-action …

Add new `packages` field to corral.json

---

.release-notes/171.md
corral/cmd/constraints.pony

We are in the process of switching ponylang repos over from `master`
to `main` as the default branch to match GitHub's change for the
default name for new repos.
This commit switches corral to be in line with the new GitHub defaults.

Switch default branch to use when none is supplied to 'main`

---

.ci-scripts/freebsd-12.2-install-pony-tools.bash

We were using a nightly version of FreeBSD-12.2 of ponyc as there
was no release version yet.

Install release version of ponyc for FreeBSD

---

.release-notes/184.md
corral/cmd/cmd_run.pony
corral/vcs/git.pony

This change is backwards compatible with ponyc 0.40.0

Update to match breaking API change in the pony standard library

---

corral/test/util.pony

This was always seen on Windows where integration tests would sometimes
fail because the test file to be used hadn't yet been closed by it's
setup so it was unavailable to be used and we would get this error
hidden in stdout:
2021-07-15T03:49:18.1791520Z The process cannot access the file
'D:\a\corral\corral\test_scratch.ew7i6j\scripted\test.ps1' because it is
being used

Fix flakey test setup

---

.release-notes/update-finishes-correct.md
corral/cmd/cmd_update.pony

When a dependency had a version constraint rather than a single value,
the first time `corral update` was run, you wouldn't end up with the
correct code checked out. The constraint was correctly solved, but the
checked out code would be for branch `main`.
The problem arose because we first have to check something out and then
can do constraint solving.
This commit makes the change to keep track of what "something" was that
was initially checked out and if it differs from what we eventually
determine the revision should be, we run another update to get the
contents of `_corral` into the correct state.

Fixed bug where `corral update` would result in incorrect code in the corral

---

.release-notes/dont-error.md
corral/cmd/cmd_update.pony

Previously fetch would print a warning if a transitive dependency was missing
its corral.json. By not erroring out, it made corral usable with libraries that
are corral ignorant. However, update was set to error out, meaning that you
couldn't use it with corral ignorant libraries.
The previous version of corral switched fetch to being exactly the same as
update and in the process we picked up this unwanted erroring out.
This update switched update to issue a warning like fetch previously did.

Don't error out if a transitive dependency doesn't have a corral.json

---

.ci-scripts/freebsd-13.0-install-pony-tools.bash
.cirrus.yml
corral/bundle/project.pony
corral/cmd/_test_cmd_update.pony
corral/cmd/cmd_pack.pony
corral/cmd/executor.pony
corral/cmd/repo.pony
corral/test/util.pony
corral/util/action.pony

Changes are all related to RFC 70.
Once the next version of ponyc is released, PR CI tasks need to be
switched back from using nightly to release.

Update corral to work with latest ponyc nightly

---

make.ps1

- Add a "buildtest" command to build tests without running them.
- Force the test executable to be "test.exe".

Refinements to Windows build script

---

.release-notes/216.md
CHANGELOG.md
corral/cmd/cmd_run.pony
corral/test/_test.pony
corral/test/integration/test_run.pony
corral/test/util.pony
corral/util/action.pony

The logic to determine the absolute path to an executable was using `FilePath.from(base, subdir)` which errors if the resulting path is not below the `base`. This is the case if `subdir` is e.g. `../foo`.
This fix stems from trying to execute:
```
$ corral run -- ../../ponyc/build/debug/ponyc
run: couldn't run program: ../../ponyc/build/debug/ponyc .
```
The error output is clearly not really informative.
With this PR the above command actually runs the existing ponyc.
Other changes in here all related to improving `corral run`:
* First try to resolve relative paths against the current working directory, then against `$PATH`. This enables running relative paths to parent folders (See the above command).
* Display different errors if no args were provided or the executable to run could not …

Fix resolving relative paths with `corral run`

---

.ci-scripts/MacOS-arm64-install-pony-tools.bash
.ci-scripts/release/arm64-apple-darwin-nightly.bash
.cirrus.yml

We don't need the PR check here except to validate that the installation
process for ponyc works. I'll remove the PR step once we are fully up
and running and using ponyup.

Add nightly builds for MacOS on Apple Silicon

---

.release-notes/alpine-316.md
Dockerfile

Previously we were using 3.12 which is no longer supported.

Update Dockerfile to use Alpine 3.16 as base

---

.cirrus.yml

It was on nightly until the first ponyc for FreeBSD 13.1 was released.

Set FreeBSD back to using release ponyc

---

.github/workflows/breakage-against-macOS-ponyc-latest.yml
.github/workflows/breakage-against-windows-ponyc-latest.yml
make.ps1

The integration tests are likely to spuriously fail due to GitHub issues. The unit tests give us the breakage coverage that we really need and won't spuriously fail. This lack of a chance to fail "randomly" means we won't be training people to ignore breakage test failures.

Only run unit tests when doing breakage tests against new ponyc nightlies

---

.ci-scripts/release/build-docker-images-on-release.bash
.ci-scripts/release/build-latest-docker-images.bash
.github/workflows/latest-docker-image.yml
.github/workflows/release.yml

We are transitioning from DockerHub to GitHub Container Registry. As part of this transition, we will have a period of time where we push all images to both registries.
This commit updates corral to push its public images of latest and release builds to GitHub Container Registry and DockerHub.
In addition, it adds a job to run after the latest docker image is pushed to prune old "latest" images that have become "untagged" and shouldn't be being used any longer.

Push public Docker images to GitHub Container Registry

---

README.md

$PATH environment variable is very Unix specific. The update makes this general and more applicable to Windows.
Closes #93

Update installation instructions to not be Unix specific

---

.ci-scripts/release/build-docker-images-on-release.bash
.ci-scripts/release/build-latest-docker-images.bash
.github/workflows/latest-docker-image.yml
.github/workflows/release.yml

We've migrated off of DockerHub and all new images are stored only in the GitHub Container Registry.

Stop pushing new images to DockerHub

---

.ci-scripts/macos-arm64-install-pony-tools.bash
.github/workflows/pr.yml
.github/workflows/release.yml

We were using nightlies as we had no recent ponyc releases until 0.58.2 went out today.

Use release ponyc version for Apple Silicon MacOS releases

---

.release-notes/275.md
corral/cli.pony

There was a bug in corral's handling of the the `-d` command line option. The default value was set to the string "<cwd>". This would result in corral.json not being found.
The bug wasn't triggered because a bug in the Pony standard library prevented the default value from correctly being applied. Once that bug was fixed, corral stopped working unless a `-d` value was provided.

Fix bug with default bundle directory handling
